// Default Russian word list for ru-key typing trainer.
// Format: comma-separated entries, each "слово=english meaning".
// Roughly ordered by frequency (most common first) — the app samples
// with a bias toward the beginning of the list.
const DEFAULT_WORDS = `
и=and,в=in,не=not,на=on,я=I,быть=to be,он=he,с=with,что=what,а=but,
это=this,она=she,этот=this one,к=to,но=but,они=they,мы=we,как=how,из=from,у=at,
который=which,то=that,за=behind,свой=one's own,весь=all,год=year,от=from,так=so,о=about,для=for,
ты=you,же=indeed,все=everyone,тот=that one,мочь=to be able,вы=you (plural),человек=person,такой=such,его=his,сказать=to say,
только=only,или=or,ещё=still,бы=would,себя=oneself,один=one,уже=already,до=until,время=time,если=if,
сам=oneself,когда=when,другой=other,вот=here is,говорить=to speak,наш=our,мой=my,знать=to know,стать=to become,чтобы=in order to,
дело=matter,жизнь=life,кто=who,первый=first,очень=very,два=two,день=day,её=her,новый=new,рука=hand,
даже=even,раз=occasion,где=where,там=there,под=under,можно=one can,ну=well,какой=which kind,после=after,их=their,
работа=work,без=without,самый=the most,потом=then,надо=necessary,хотеть=to want,ли=whether,слово=word,идти=to go,большой=big,
должен=must,место=place,иметь=to have,ничего=nothing,теперь=now,тоже=also,видеть=to see,вопрос=question,через=through,да=yes,
здесь=here,дом=house,мир=world,есть=to eat,вместе=together,сейчас=right now,голова=head,тогда=then,ребёнок=child,сила=strength,
конец=end,вид=view,система=system,часть=part,город=city,дать=to give,думать=to think,сделать=to do,страна=country,жить=to live,
чем=than,мама=mom,право=right,нет=no,хорошо=well,ваш=your,потому=because,сторона=side,просто=simply,нога=leg,
сидеть=to sit,понять=to understand,конечно=of course,оба=both,писать=to write,лицо=face,что-то=something,пойти=to set off,женщина=woman,машина=car,
случай=case,ночь=night,сразу=immediately,никто=nobody,перед=in front of,деньги=money,взять=to take,хотя=although,три=three,решить=to decide,
именно=exactly,найти=to find,отец=father,спросить=to ask,вода=water,земля=earth,начать=to begin,остаться=to remain,каждый=each,глаз=eye,
стоять=to stand,месяц=month,всегда=always,история=history,почти=almost,друг=friend,увидеть=to catch sight of,куда=where to,русский=Russian,образ=image,
казаться=to seem,класс=class,общий=common,несколько=several,квартира=apartment,отношение=relation,группа=group,давать=to give,начало=beginning,бог=god,
назад=back,процесс=process,область=region,больше=more,пока=for now,отвечать=to answer,всё=everything,война=war,муж=husband,правда=truth,
получить=to receive,любить=to love,душа=soul,взгляд=glance,минута=minute,играть=to play,читать=to read,письмо=letter,подумать=to ponder,утро=morning,
ходить=to walk,белый=white,век=century,причина=reason,оказаться=to turn out,путь=path,чувствовать=to feel,брать=to take,успеть=to be in time,центр=center,
проблема=problem,форма=form,помнить=to remember,общество=society,чёрный=black,бывать=to happen,семья=family,интерес=interest,показать=to show,театр=theater,
положение=position,молодой=young,просить=to request,оставить=to leave,окно=window,похожий=similar,момент=moment,цель=goal,спать=to sleep,народ=people,
высокий=tall,находиться=to be located,этаж=storey,собственный=personal,мужчина=man,подойти=to approach,комната=room,игра=game,поле=field,книга=book,
школа=school,улица=street,ответ=answer,уровень=level,час=hour,начаться=to start,держать=to hold,речь=speech,имя=name,вечер=evening,
особенно=especially,снова=again,узнать=to find out,равный=equal,кроме=besides,огромный=huge,пример=example,люди=people (plural),стол=table,крупный=large,
произойти=to occur,хороший=good,дверь=door,число=number,появиться=to appear,смотреть=to look,ребята=guys,разговор=conversation,уйти=to leave,развитие=development,
выйти=to exit,много=many,значит=it means,против=against,совсем=completely,открыть=to open,менее=less,государство=state,язык=language,любой=any,
ждать=to wait,точно=precisely,вспомнить=to recall,результат=result,гость=guest,власть=power,закон=law,всякий=any kind of,труд=labor,значить=to mean,
понимать=to comprehend,второй=second,приехать=to arrive by vehicle,армия=army,берег=shore,мысль=thought,идея=idea,взяться=to undertake,провести=to conduct,помощь=help,
добрый=kind,честь=honor,палец=finger,неделя=week,лучше=better,смочь=to manage,условие=condition,прийти=to come,пора=it is time,главный=main,
сердце=heart,движение=movement,попасть=to get into,разный=various,рынок=market,известный=well-known,федерация=federation,надежда=hope,счёт=account,суд=court,
море=sea,российский=Russian (adjective),статья=article,институт=institute,план=plan,характер=character,ряд=row,связь=connection,желание=desire,порядок=order,
получиться=to work out,отдать=to give back,единый=unified,ветер=wind,мера=measure,дорога=road,край=edge,километр=kilometer,функция=function,состояние=condition,
завод=factory,кровь=blood,внимание=attention,возможность=possibility,данные=data,попробовать=to try,волос=hair,общественный=public,бумага=paper,тема=theme,
успех=success,политика=politics,свет=light,снять=to take off,картина=picture,производство=production,широкий=wide,давно=long ago,служба=service,бой=battle,
председатель=chairman,цена=price,информация=information,мнение=opinion,улыбнуться=to smile,энергия=energy,структура=structure,гора=mountain,товарищ=comrade,вернуться=to return,
способ=method,плечо=shoulder,шаг=step,золотой=golden,культура=culture,парень=guy,наука=science,принцип=principle,музыка=music,лежать=to lie down,
цветок=flower,искать=to search,наконец=finally,птица=bird,территория=territory,положить=to put down,приходиться=to have to,судьба=fate,вполне=quite,вести=to lead,
зал=hall,удаться=to succeed,площадь=square,создать=to create,отдел=department,бросить=to throw,детский=children's,лес=forest,составлять=to constitute,зачем=what for,
объяснить=to explain,объект=object,подъезд=building entrance,съесть=to eat up,объём=volume,съезд=congress,объявление=announcement,субъект=subject,въезд=entry,объединить=to unite,
жена=wife,сын=son,дочь=daughter,брат=brother,сестра=sister,бабушка=grandmother,дедушка=grandfather,дядя=uncle,тётя=aunt,родители=parents,
внук=grandson,внучка=granddaughter,племянник=nephew,двоюродный=cousin (adjective),свадьба=wedding,жених=groom,невеста=bride,семейный=family (adjective),родной=native,близкий=close,
тело=body,спина=back,живот=stomach,грудь=chest,шея=neck,ухо=ear,нос=nose,рот=mouth,губа=lip,зуб=tooth,
затылок=back of the head,лоб=forehead,щека=cheek,бровь=eyebrow,колено=knee,локоть=elbow,ладонь=palm,кожа=skin,кость=bone,мышца=muscle,
хлеб=bread,молоко=milk,мясо=meat,рыба=fish,сыр=cheese,масло=butter,яйцо=egg,сахар=sugar,соль=salt,перец=pepper,
суп=soup,каша=porridge,блюдо=dish,завтрак=breakfast,обед=lunch,ужин=dinner,чай=tea,кофе=coffee,сок=juice,вино=wine,
яблоко=apple,груша=pear,виноград=grapes,арбуз=watermelon,ягода=berry,овощ=vegetable,фрукт=fruit,картофель=potato,морковь=carrot,капуста=cabbage,
огурец=cucumber,помидор=tomato,лук=onion,чеснок=garlic,гриб=mushroom,орех=nut,мёд=honey,торт=cake,печенье=cookies,шоколад=chocolate,
собака=dog,кошка=cat,лошадь=horse,корова=cow,свинья=pig,овца=sheep,коза=goat,курица=chicken,утка=duck,гусь=goose,
волк=wolf,медведь=bear,лиса=fox,заяц=hare,ёж=hedgehog,белка=squirrel,олень=deer,лось=moose,мышь=mouse,крыса=rat,
слон=elephant,тигр=tiger,лев=lion,обезьяна=monkey,жираф=giraffe,змея=snake,лягушка=frog,бабочка=butterfly,пчела=bee,муравей=ant,
паук=spider,комар=mosquito,муха=fly,жук=beetle,червяк=worm,орёл=eagle,ворона=crow,воробей=sparrow,голубь=pigeon,сова=owl,
небо=sky,солнце=sun,луна=moon,звезда=star,облако=cloud,дождь=rain,снег=snow,туман=fog,гроза=thunderstorm,молния=lightning,
река=river,озеро=lake,океан=ocean,остров=island,пустыня=desert,долина=valley,скала=cliff,камень=stone,песок=sand,трава=grass,
дерево=tree,берёза=birch,дуб=oak,сосна=pine,ёлка=fir tree,лист=leaf,корень=root,ветка=branch,семя=seed,почва=soil,
весна=spring,лето=summer,осень=autumn,зима=winter,январь=January,февраль=February,март=March,апрель=April,май=May,июнь=June,
июль=July,август=August,сентябрь=September,октябрь=October,ноябрь=November,декабрь=December,понедельник=Monday,вторник=Tuesday,среда=Wednesday,четверг=Thursday,
пятница=Friday,суббота=Saturday,воскресенье=Sunday,сегодня=today,завтра=tomorrow,вчера=yesterday,сутки=twenty-four hours,полдень=noon,полночь=midnight,рассвет=dawn,
красный=red,синий=dark blue,голубой=light blue,зелёный=green,жёлтый=yellow,оранжевый=orange,фиолетовый=purple,розовый=pink,серый=gray,коричневый=brown,
маленький=small,длинный=long,короткий=short,низкий=low,толстый=thick,тонкий=thin,тяжёлый=heavy,лёгкий=light,быстрый=fast,медленный=slow,
горячий=hot,холодный=cold,тёплый=warm,сухой=dry,мокрый=wet,чистый=clean,грязный=dirty,пустой=empty,полный=full,громкий=loud,
тихий=quiet,яркий=bright,тёмный=dark,светлый=light-colored,сильный=strong,слабый=weak,твёрдый=hard,мягкий=soft,острый=sharp,тупой=blunt,
дорогой=expensive,дешёвый=cheap,богатый=rich,бедный=poor,счастливый=happy,грустный=sad,весёлый=cheerful,злой=angry,умный=smart,глупый=stupid,
красивый=beautiful,страшный=scary,интересный=interesting,скучный=boring,важный=important,простой=simple,сложный=complex,трудный=difficult,свободный=free,занятый=busy,
старый=old,древний=ancient,современный=modern,прошлый=past,будущий=future,ранний=early,поздний=late,частый=frequent,редкий=rare,вечный=eternal,
врач=doctor,учитель=teacher,инженер=engineer,водитель=driver,повар=cook,продавец=salesperson,строитель=builder,художник=artist,писатель=writer,актёр=actor,
певец=singer,музыкант=musician,юрист=lawyer,судья=judge,полицейский=policeman,пожарный=firefighter,солдат=soldier,офицер=officer,директор=director,начальник=boss,
рабочий=worker,крестьянин=peasant,учёный=scientist,студент=student,ученик=pupil,профессор=professor,переводчик=translator,журналист=journalist,фотограф=photographer,программист=programmer,
магазин=shop,аптека=pharmacy,больница=hospital,банк=bank,почта=post office,ресторан=restaurant,кафе=cafe,гостиница=hotel,музей=museum,библиотека=library,
церковь=church,собор=cathedral,храм=temple,памятник=monument,мост=bridge,башня=tower,крепость=fortress,дворец=palace,парк=park,сад=garden,
вокзал=train station,аэропорт=airport,остановка=bus stop,метро=subway,автобус=bus,трамвай=tram,троллейбус=trolleybus,поезд=train,самолёт=airplane,корабль=ship,
лодка=boat,велосипед=bicycle,мотоцикл=motorcycle,грузовик=truck,такси=taxi,билет=ticket,багаж=luggage,чемодан=suitcase,паспорт=passport,виза=visa,
путешествие=journey,поездка=trip,отпуск=vacation,туризм=tourism,карта=map,граница=border,таможня=customs,рейс=flight,маршрут=route,расписание=schedule,
кухня=kitchen,спальня=bedroom,ванная=bathroom,туалет=toilet,коридор=hallway,балкон=balcony,потолок=ceiling,стена=wall,пол=floor,крыша=roof,
лестница=staircase,лифт=elevator,ключ=key,замок=lock,мебель=furniture,стул=chair,кресло=armchair,диван=sofa,кровать=bed,шкаф=wardrobe,
полка=shelf,зеркало=mirror,ковёр=carpet,занавеска=curtain,лампа=lamp,подушка=pillow,одеяло=blanket,простыня=bedsheet,полотенце=towel,мыло=soap,
посуда=dishes,тарелка=plate,чашка=cup,стакан=glass,ложка=spoon,вилка=fork,ножик=small knife,кастрюля=pot,сковорода=frying pan,чайник=kettle,
холодильник=refrigerator,плита=stove,духовка=oven,стиральная=washing (adjective),пылесос=vacuum cleaner,утюг=iron,ведро=bucket,метла=broom,мусор=garbage,уборка=cleaning,
одежда=clothing,рубашка=shirt,футболка=t-shirt,свитер=sweater,куртка=jacket,пальто=coat,платье=dress,юбка=skirt,брюки=trousers,джинсы=jeans,
носки=socks,обувь=footwear,ботинки=boots,туфли=shoes,кроссовки=sneakers,шапка=hat,шарф=scarf,перчатки=gloves,ремень=belt,карман=pocket,
пуговица=button,пряжка=buckle,очки=glasses,часы=watch,кольцо=ring,серьга=earring,браслет=bracelet,сумка=bag,рюкзак=backpack,зонт=umbrella,
компьютер=computer,ноутбук=laptop,телефон=phone,экран=screen,клавиатура=keyboard,мышка=computer mouse,кнопка=button (key),файл=file,папка=folder,программа=program,
интернет=internet,сайт=website,сеть=network,пароль=password,сообщение=message,конверт=envelope,печать=printing,принтер=printer,камера=camera,наушники=headphones,
телевизор=television,радио=radio,новости=news,газета=newspaper,журнал=magazine,реклама=advertisement,канал=channel,передача=broadcast,фильм=movie,сериал=TV series,
радость=joy,грусть=sadness,страх=fear,гнев=anger,удивление=surprise,стыд=shame,гордость=pride,зависть=envy,жалость=pity,скука=boredom,
любовь=love,ненависть=hatred,дружба=friendship,доверие=trust,уважение=respect,забота=care,нежность=tenderness,ревность=jealousy,обида=resentment,прощение=forgiveness,
счастье=happiness,горе=grief,удача=luck,беда=trouble,опасность=danger,риск=risk,страдание=suffering,удовольствие=pleasure,наслаждение=delight,восторг=rapture,
память=memory,разум=reason (mind),сознание=consciousness,мечта=dream (wish),сон=sleep,воображение=imagination,знание=knowledge,мудрость=wisdom,опыт=experience,талант=talent,
университет=university,факультет=faculty,лекция=lecture,урок=lesson,экзамен=exam,оценка=grade,задание=assignment,ошибка=mistake,правило=rule,словарь=dictionary,
тетрадь=notebook,ручка=pen,карандаш=pencil,линейка=ruler,доска=chalkboard,мел=chalk,учебник=textbook,страница=page,глава=chapter,текст=text,
буква=letter (character),предложение=sentence,рассказ=story,роман=novel,стихотворение=poem,сказка=fairy tale,герой=hero,автор=author,читатель=reader,перевод=translation,
спорт=sport,футбол=football,хоккей=hockey,теннис=tennis,шахматы=chess,плавание=swimming,бег=running,прыжок=jump,матч=match,команда=team,
игрок=player,тренер=coach,победа=victory,поражение=defeat,приз=prize,медаль=medal,чемпион=champion,соревнование=competition,стадион=stadium,бассейн=swimming pool,
здоровье=health,болезнь=illness,лекарство=medicine,таблетка=pill,укол=injection,температура=temperature,кашель=cough,насморк=runny nose,боль=pain,рана=wound,
праздник=holiday,подарок=gift,гостиная=living room,торжество=celebration,юбилей=anniversary,поздравление=congratulation,цирк=circus,концерт=concert,спектакль=performance,выставка=exhibition,
щука=pike (fish),щенок=puppy,щётка=brush,щи=cabbage soup,площадка=playground,ящик=box,товарищество=partnership,общение=communication,вещь=thing,помещение=premises,
цифра=digit,цирюльник=barber (old word),цыплёнок=chick,целый=whole,цитата=quotation,конституция=constitution,станция=station,милиция=militia,операция=operation,традиция=tradition,
фабрика=factory (light industry),фамилия=surname,февральский=February (adjective),фонарь=lantern,форточка=window vent,флаг=flag,флот=fleet,фраза=phrase,фонтан=fountain,профессия=profession,
эхо=echo,экономика=economy,экскурсия=excursion,элемент=element,этап=stage,этика=ethics,юг=south,юность=youth,юмор=humor,яд=poison
`;
